"""Add is_admin to users

Revision ID: 479600a2661d
Revises: 944f25e94662
Create Date: 2026-03-20 21:41:00.883848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479600a2661d'
down_revision = '944f25e94662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
